#!/bin/sh

# distro tests appear to be intentional to fail:
# https://github.com/celery/celery/issues/2517
# integration tests require a rabbitmq-server:
# https://github.com/celery/celery/issues/3917

set -e
for p in $(py3versions -s); do
    $p -m pytest -k-test_sphinx -k-DatabaseBackend -k-test_worker  -p celery.contrib.pytest --ignore t/distro --ignore t/integration t
done
