#!/bin/sh

# distro tests appear to be intentional to fail:
# https://github.com/celery/celery/issues/2517
# integration tests require a rabbitmq-server:
# https://github.com/celery/celery/issues/3917

for p in $(pyversions -s); do
    $p $(which pytest) -k-test_sphinx --ignore t/distro --ignore t/integration t
done

for p in $(py3versions -s); do
    $p $(which pytest-3) -k-test_sphinx --ignore t/distro --ignore t/integration t
done
